#### general settings
name: ModelTest
use_tb_logger: false #true
model: VideoSR_base
distortion: sr
scale: 4
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: FootballVids
    mode: FootballVids
    interval_list: [1]
    random_reverse: true #false
    border_mode: false
    dataroot_GT: /vol/bitbucket/nr421/project-zsm-new/codes/data/footballvids_train_HR.lmdb
    dataroot_LQ: /vol/bitbucket/nr421/project-zsm-new/codes/data/footballvids_train_LR.lmdb
    cache_keys: FootballVids_train_keys.pkl 

    N_frames: 5
    use_shuffle: true
    n_workers: 3  # per GPU
    batch_size: 8 
    GT_size: 128 
    LQ_size: 32
    use_flip: true
    use_rot: true
    color: RGB

#### network structures
network_G:
  which_model_G: LunaTokis
  nf: 64
  nframes: 5
  groups: 8
  front_RBs: 5
  mid_RBs: 0
  back_RBs: 40
  HR_in: false

#### path
path:
  pretrain_model_G: ~ 
  strict_load: false #true #
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 600000
  warmup_iter: -1 #4000  # -1: no warm up
  T_period: [150000, 150000, 150000, 150000]
  restarts: [150000, 300000, 450000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 5e3

  manual_seed: 0

#### logger
logger:
  print_freq: 25
  save_checkpoint_freq: 1500
